dict_disease_category = {
    'thuoc-tuan-hoan-mau-nao': '304',
    'thuoc-tri-gian-tinh-mach-tri-tri': '301',
    'thuoc-tieu-duong': '297',
    'thuoc-tay-giun-san': '295',
    'thuoc-roi-loan-cuong-duong': '292',
    'thuoc-khang-sinh-khang-virut': '288',
    'thuoc-hen-suyen': '285',
    # 'thuoc-giam-dau-khang-viem': '289',
    'thuoc-duong-tieu-hoa': '280',
    'thuoc-co-nguon-goc-tu-tu-nhien': '277',
    # 'thuoc-cam-mau': '',
    # 'thuoc-tri-ung-thu-u-buou': '',
    'thuoc-tranh-thai': '300',
    # 'thuoc-tiem-dich-truyen': '',
    'thuoc-tai-mui-hong': '294',
    'thuoc-phu-khoa': '291',
    'thuoc-khang-nam': '287',
    'thuoc-ha-mo-mau-ha-cholesterol': '284',
    'thuoc-giam-dau-ha-sot': '282',
    'thuoc-duong-tiet-nieu': '279',
    # 'thuoc-chong-say-xe': '',
    'thuoc-bo-vitamin-va-khoang-chat': '273',
    'thuoc-tri-gut-xuong-khop': '302',
    'thuoc-tim-mach': '298',
    'thuoc-than-kinh-tram-cam-dong-kinh-parkinson': '299',
    'thuoc-roi-loan-tien-dinh': '293',
    'thuoc-nho-mat-tra-mat': '290',
    'thuoc-ho-long-dom': '286',
    'thuoc-gian-co': '283',
    'thuoc-gan-mat': '281',
    'thuoc-da-lieu' : '278',
    'thuoc-chong-di-ung-khang-histamin' : '275',
    'hocmon-noi-tiet-to': '310',
    # 'dung-dich-sat-trung': '306'
}